### ISSUE TITLE
public lobby bug

### ISSUE THREAD

**Issue by FireNinja7365** [19miffyliu/Sprint_Multiplier#2]
when you first join the game and if you go into a public lobby it breaks entirely and makes you super slow, but if you host a lobby first and then go into a public lobby it works fine, so can you please fix it so i don't have to host a lobby just to fix a bug before playing in public lobbies

**Comment by 19miffyliu** [comment]
That is a...very specific and weird bug. 
Does the public lobby's host have this mod enabled? If yes, then I may have to fix the bug. If no, then having the host enabling it may fix the issue.

I didn't even know that you can join a public lobby with this mod enabled, because this mod is _not_ a client-side mod--every player in the lobby (the host and clients) needs to enable it for it to work properly.

**Comment by FireNinja7365** [comment]
normally speaking the host doesn't have the mod, and the speed still works(if you host a lobby before hand) but if if you just join a public lobby without hosting a lobby before hand it breaks and makes it so sprint speed is super slow. if you could do you think you could make an only client side version of the mod?

**Comment by 19miffyliu** [comment]
I'm afraid I cannot make a client-side version of this mod because of 1) I don't know how and 2) ethical issues.
1) If you look closely at client-side mods on thunderstore, you can see that client-side mods are generally UI mods such as better scans and healthbar HUD: they only _display_ information, not changing them. That is because when the host opens a lobby, the game will run on the host's mod settings, and clients will only have read-only access to the game data. 
This mod modifies the speed of the player, which is in the game data, so the mod should not work if the host did not enable it. I was very surprised that you were able to modify your speed as a client--you normally cannot do that.

2) Even if I _can_ , I would not do it for possible exploitation. Imagine a case where you and your friends opened a public lobby to have some normal fun, and someone joined with super speed. They started throwing the scraps off a cliff or luring the dog towards your friends or bullying people with a shovel and there's nothing you can do to stop them...I'm not saying that random players are bad--players in this community are lovely, but I would suggest _not_ using it in public lobbies, or at least check with the host first before using it.
